services:
  app:
    image: dmitrysvd1/wishes-app:latest
    command: >
      uv run gunicorn
        --bind 0.0.0.0:8000
        --worker-class uvicorn.workers.UvicornWorker
        --workers 1
        --forwarded-allow-ips='*'
        --chdir /app
        --access-logfile -
        --error-logfile -
        app.main:app
    volumes:
      - ./static:/app/static:ro
      - /data/media:/media
      - ./firebase-adminsdk.json:/firebase-adminsdk.json:ro
      - ./db.sqlite:/app/db.sqlite
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  db:
    image: postgres:18
    container_name: wishes-db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:
