services:
  app:
    image: dmitrysvd1/wishes-app:latest
    # build:
    #   context: .
    #   target: dev
    command: >
      uv run gunicorn
        --bind 0.0.0.0:8000
        --worker-class uvicorn.workers.UvicornWorker
        --workers 1
        --forwarded-allow-ips='*'
        --chdir /app
        --access-logfile -
        --error-logfile -
        app.main:app
    volumes:
      - ./static:/app/static:ro
      - ./media:/app/media
      - ./firebase-adminsdk.json:/firebase-adminsdk.json:ro
      - ./db.sqlite:/app/db.sqlite
      - ./db.sqlite-shm:/app/db.sqlite-shm
      - ./db.sqlite-wal:/app/db.sqlite-wal
    ports:
      - "127.0.0.1:8000:8000"
    # depends_on:
    #   - db
    env_file: .env
    restart: always

#   db:
#     image: postgres:18
#     container_name: wishes-db
#     restart: always
#     env_file: .env
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/

# volumes:
#   postgres_data: