services:
  app:
    image: dmitrysvd1/wishes-app:latest
    # build:
    #   context: .
    #   target: dev
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./static:/app/static:ro
      - ./media:/app/media
      - ./firebase-adminsdk.json:/firebase-adminsdk.json:ro
      - ./db.sqlite:/app/db.sqlite
      - ./db.sqlite-shm:/app/db.sqlite-shm
      - ./db.sqlite-wal:/app/db.sqlite-wal
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    env_file: .env

#   db:
#     image: postgres:18
#     container_name: wishes-db
#     restart: always
#     env_file: .env
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/

# volumes:
#   postgres_data: